// Code generated by Slice Machine. DO NOT EDIT.

import type * as prismic from "@prismicio/client";

type Simplify<T> = { [KeyType in keyof T]: T[KeyType] };

/**
 * Item in *Footer → Colonne 1*
 */
export interface FooterDocumentDataColonne1Item {
  /**
   * Lien field in *Footer → Colonne 1*
   *
   * - **Field Type**: Content Relationship
   * - **Placeholder**: *None*
   * - **API ID Path**: footer.colonne_1[].lien
   * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
   */
  lien: prismic.ContentRelationshipField;

  /**
   * Label field in *Footer → Colonne 1*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: footer.colonne_1[].label
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  label: prismic.KeyTextField;
}

/**
 * Item in *Footer → Colonne 2*
 */
export interface FooterDocumentDataColonne2Item {
  /**
   * Lien field in *Footer → Colonne 2*
   *
   * - **Field Type**: Content Relationship
   * - **Placeholder**: *None*
   * - **API ID Path**: footer.colonne_2[].lien
   * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
   */
  lien: prismic.ContentRelationshipField;

  /**
   * Label field in *Footer → Colonne 2*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: footer.colonne_2[].label
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  label: prismic.KeyTextField;
}

/**
 * Item in *Footer → Colonne 3*
 */
export interface FooterDocumentDataColonne3Item {
  /**
   * Lien field in *Footer → Colonne 3*
   *
   * - **Field Type**: Content Relationship
   * - **Placeholder**: *None*
   * - **API ID Path**: footer.colonne_3[].lien
   * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
   */
  lien: prismic.ContentRelationshipField;

  /**
   * Label field in *Footer → Colonne 3*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: footer.colonne_3[].label
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  label: prismic.KeyTextField;
}

/**
 * Item in *Footer → Bottom*
 */
export interface FooterDocumentDataBottomItem {
  /**
   * Lien field in *Footer → Bottom*
   *
   * - **Field Type**: Content Relationship
   * - **Placeholder**: *None*
   * - **API ID Path**: footer.bottom[].lien
   * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
   */
  lien: prismic.ContentRelationshipField;

  /**
   * Label field in *Footer → Bottom*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: footer.bottom[].label
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  label: prismic.KeyTextField;
}

/**
 * Content for Footer documents
 */
interface FooterDocumentData {
  /**
   * Colonne 1 field in *Footer*
   *
   * - **Field Type**: Group
   * - **Placeholder**: *None*
   * - **API ID Path**: footer.colonne_1[]
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#group
   */
  colonne_1: prismic.GroupField<Simplify<FooterDocumentDataColonne1Item>>;

  /**
   * Colonne 2 field in *Footer*
   *
   * - **Field Type**: Group
   * - **Placeholder**: *None*
   * - **API ID Path**: footer.colonne_2[]
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#group
   */
  colonne_2: prismic.GroupField<Simplify<FooterDocumentDataColonne2Item>>;

  /**
   * Colonne 3 field in *Footer*
   *
   * - **Field Type**: Group
   * - **Placeholder**: *None*
   * - **API ID Path**: footer.colonne_3[]
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#group
   */
  colonne_3: prismic.GroupField<Simplify<FooterDocumentDataColonne3Item>>;

  /**
   * Bottom field in *Footer*
   *
   * - **Field Type**: Group
   * - **Placeholder**: *None*
   * - **API ID Path**: footer.bottom[]
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#group
   */
  bottom: prismic.GroupField<Simplify<FooterDocumentDataBottomItem>>;

  /**
   * Texte reseaux field in *Footer*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: footer.texte_reseaux
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  texte_reseaux: prismic.KeyTextField;

  /**
   * Facebook field in *Footer*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: footer.facebook
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  facebook: prismic.KeyTextField;

  /**
   * Linkedin field in *Footer*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: footer.linkedin
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  linkedin: prismic.KeyTextField;

  /**
   * Instagram field in *Footer*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: footer.instagram
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  instagram: prismic.KeyTextField;

  /**
   * Texte field in *Footer*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: footer.texte
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  texte: prismic.RichTextField;

  /**
   * Label lien field in *Footer*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: footer.label_lien
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  label_lien: prismic.KeyTextField;

  /**
   * Url lien field in *Footer*
   *
   * - **Field Type**: Link
   * - **Placeholder**: *None*
   * - **API ID Path**: footer.url_lien
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
   */
  url_lien: prismic.LinkField;

  /**
   * Logo field in *Footer*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: footer.logo
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  logo: prismic.ImageField<never>;
}

/**
 * Footer document from Prismic
 *
 * - **API ID**: `footer`
 * - **Repeatable**: `false`
 * - **Documentation**: https://prismic.io/docs/custom-types
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type FooterDocument<Lang extends string = string> =
  prismic.PrismicDocumentWithoutUID<
    Simplify<FooterDocumentData>,
    "footer",
    Lang
  >;

/**
 * Item in *Header → navigation*
 */
export interface HeaderDocumentDataNavigationItem {
  /**
   * lien field in *Header → navigation*
   *
   * - **Field Type**: Content Relationship
   * - **Placeholder**: *None*
   * - **API ID Path**: header.navigation[].lien
   * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
   */
  lien: prismic.ContentRelationshipField;

  /**
   * Label field in *Header → navigation*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: header.navigation[].label
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  label: prismic.KeyTextField;
}

/**
 * Content for Header documents
 */
interface HeaderDocumentData {
  /**
   * Url localisation field in *Header*
   *
   * - **Field Type**: Content Relationship
   * - **Placeholder**: *None*
   * - **API ID Path**: header.url_localisation
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
   */
  url_localisation: prismic.ContentRelationshipField;

  /**
   * navigation field in *Header*
   *
   * - **Field Type**: Group
   * - **Placeholder**: *None*
   * - **API ID Path**: header.navigation[]
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#group
   */
  navigation: prismic.GroupField<Simplify<HeaderDocumentDataNavigationItem>>;

  /**
   * Label bouton field in *Header*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: header.label_bouton
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  label_bouton: prismic.KeyTextField;

  /**
   * Url bouton field in *Header*
   *
   * - **Field Type**: Link
   * - **Placeholder**: *None*
   * - **API ID Path**: header.url_bouton
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
   */
  url_bouton: prismic.LinkField;
}

/**
 * Header document from Prismic
 *
 * - **API ID**: `header`
 * - **Repeatable**: `false`
 * - **Documentation**: https://prismic.io/docs/custom-types
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type HeaderDocument<Lang extends string = string> =
  prismic.PrismicDocumentWithoutUID<
    Simplify<HeaderDocumentData>,
    "header",
    Lang
  >;

type HomepageDocumentDataSlicesSlice =
  | ContactSlice
  | SliderSlice
  | BaniereLogoSlice
  | TitreSlice
  | MediaSlice
  | TestSlice
  | RealisationsSlice
  | PresentationSlice
  | LieuxSlice
  | FormatSlice;

/**
 * Content for Homepage documents
 */
interface HomepageDocumentData {
  /**
   * Background logo field in *Homepage*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: homepage.background_logo
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  background_logo: prismic.ImageField<never>;

  /**
   * Logo field in *Homepage*
   *
   * - **Field Type**: Link to Media
   * - **Placeholder**: *None*
   * - **API ID Path**: homepage.logo
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
   */
  logo: prismic.LinkToMediaField;

  /**
   * Texte top field in *Homepage*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: homepage.texte_top
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  texte_top: prismic.KeyTextField;

  /**
   * Media field in *Homepage*
   *
   * - **Field Type**: Link to Media
   * - **Placeholder**: *None*
   * - **API ID Path**: homepage.media
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
   */
  media: prismic.LinkToMediaField;

  /**
   * Image backgound field in *Homepage*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: homepage.image_backgound
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  image_backgound: prismic.ImageField<never>;

  /**
   * Titre field in *Homepage*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: homepage.titre
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  titre: prismic.KeyTextField;

  /**
   * Contenu field in *Homepage*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: homepage.contenu
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  contenu: prismic.RichTextField;

  /**
   * URL lien field in *Homepage*
   *
   * - **Field Type**: Link
   * - **Placeholder**: *None*
   * - **API ID Path**: homepage.url_lien
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
   */
  url_lien: prismic.LinkField;

  /**
   * Label lien field in *Homepage*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: homepage.label_lien
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  label_lien: prismic.KeyTextField;

  /**
   * Slice Zone field in *Homepage*
   *
   * - **Field Type**: Slice Zone
   * - **Placeholder**: *None*
   * - **API ID Path**: homepage.slices[]
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#slices
   */
  slices: prismic.SliceZone<HomepageDocumentDataSlicesSlice> /**
   * Meta Title field in *Homepage*
   *
   * - **Field Type**: Text
   * - **Placeholder**: A title of the page used for social media and search engines
   * - **API ID Path**: homepage.meta_title
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */;
  meta_title: prismic.KeyTextField;

  /**
   * Meta Description field in *Homepage*
   *
   * - **Field Type**: Text
   * - **Placeholder**: A brief summary of the page
   * - **API ID Path**: homepage.meta_description
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  meta_description: prismic.KeyTextField;

  /**
   * Meta Image field in *Homepage*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: homepage.meta_image
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  meta_image: prismic.ImageField<never>;
}

/**
 * Homepage document from Prismic
 *
 * - **API ID**: `homepage`
 * - **Repeatable**: `false`
 * - **Documentation**: https://prismic.io/docs/custom-types
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type HomepageDocument<Lang extends string = string> =
  prismic.PrismicDocumentWithoutUID<
    Simplify<HomepageDocumentData>,
    "homepage",
    Lang
  >;

type PageDocumentDataSlicesSlice =
  | ContactSlice
  | SliderSlice
  | BaniereLogoSlice
  | PresentationSlice
  | MediaSlice
  | RealisationsSlice
  | FormatSlice
  | TitreSlice
  | LieuxSlice
  | TestSlice;

/**
 * Content for Page documents
 */
interface PageDocumentData {
  /**
   * Header lite field in *Page*
   *
   * - **Field Type**: Boolean
   * - **Placeholder**: *None*
   * - **Default Value**: false
   * - **API ID Path**: page.header_lite
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#boolean
   */
  header_lite: prismic.BooleanField;

  /**
   * Title field in *Page*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: page.title
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  title: prismic.KeyTextField;

  /**
   * Media field in *Page*
   *
   * - **Field Type**: Link to Media
   * - **Placeholder**: *None*
   * - **API ID Path**: page.media
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
   */
  media: prismic.LinkToMediaField;

  /**
   * Texte field in *Page*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: page.texte
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  texte: prismic.RichTextField;

  /**
   * Label lien field in *Page*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: page.label_lien
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  label_lien: prismic.KeyTextField;

  /**
   * URL lien field in *Page*
   *
   * - **Field Type**: Link
   * - **Placeholder**: *None*
   * - **API ID Path**: page.url_lien
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
   */
  url_lien: prismic.LinkField;

  /**
   * Slice Zone field in *Page*
   *
   * - **Field Type**: Slice Zone
   * - **Placeholder**: *None*
   * - **API ID Path**: page.slices[]
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#slices
   */
  slices: prismic.SliceZone<PageDocumentDataSlicesSlice> /**
   * Meta Title field in *Page*
   *
   * - **Field Type**: Text
   * - **Placeholder**: A title of the page used for social media and search engines
   * - **API ID Path**: page.meta_title
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */;
  meta_title: prismic.KeyTextField;

  /**
   * Meta Description field in *Page*
   *
   * - **Field Type**: Text
   * - **Placeholder**: A brief summary of the page
   * - **API ID Path**: page.meta_description
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  meta_description: prismic.KeyTextField;

  /**
   * Meta Image field in *Page*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: page.meta_image
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  meta_image: prismic.ImageField<never>;
}

/**
 * Page document from Prismic
 *
 * - **API ID**: `page`
 * - **Repeatable**: `true`
 * - **Documentation**: https://prismic.io/docs/custom-types
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type PageDocument<Lang extends string = string> =
  prismic.PrismicDocumentWithUID<Simplify<PageDocumentData>, "page", Lang>;

/**
 * Content for Settings documents
 */
interface SettingsDocumentData {
  /**
   * Image field in *Settings*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: settings.image
   * - **Tab**: 404
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  image: prismic.ImageField<never>;

  /**
   * Title field in *Settings*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: settings.title
   * - **Tab**: 404
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  title: prismic.KeyTextField;

  /**
   * Texte field in *Settings*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: settings.texte
   * - **Tab**: 404
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  texte: prismic.RichTextField;

  /**
   * Label field in *Settings*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: settings.label
   * - **Tab**: 404
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  label: prismic.KeyTextField;

  /**
   * Lien field in *Settings*
   *
   * - **Field Type**: Link
   * - **Placeholder**: *None*
   * - **API ID Path**: settings.lien
   * - **Tab**: 404
   * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
   */
  lien: prismic.LinkField /**
   * Site Title field in *Settings*
   *
   * - **Field Type**: Title
   * - **Placeholder**: Title of the site
   * - **API ID Path**: settings.siteTitle
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */;
  siteTitle: prismic.TitleField;

  /**
   * Favicon field in *Settings*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: settings.favicon
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  favicon: prismic.ImageField<never>;

  /**
   * Facebook field in *Settings*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: settings.facebook
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  facebook: prismic.KeyTextField;

  /**
   * Linkedin field in *Settings*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: settings.linkedin
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  linkedin: prismic.KeyTextField;

  /**
   * Instagram field in *Settings*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: settings.instagram
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  instagram: prismic.KeyTextField;

  /**
   * Whatsapp field in *Settings*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: settings.whatsapp
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  whatsapp: prismic.KeyTextField;

  /**
   * Contact field in *Settings*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: settings.contact
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  contact: prismic.KeyTextField;
}

/**
 * Settings document from Prismic
 *
 * - **API ID**: `settings`
 * - **Repeatable**: `false`
 * - **Documentation**: https://prismic.io/docs/custom-types
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type SettingsDocument<Lang extends string = string> =
  prismic.PrismicDocumentWithoutUID<
    Simplify<SettingsDocumentData>,
    "settings",
    Lang
  >;

export type AllDocumentTypes =
  | FooterDocument
  | HeaderDocument
  | HomepageDocument
  | PageDocument
  | SettingsDocument;

/**
 * Item in *BaniereLogo → Default → Primary → Images*
 */
export interface BaniereLogoSliceDefaultPrimaryImagesItem {
  /**
   * Image field in *BaniereLogo → Default → Primary → Images*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: baniere_logo.default.primary.images[].image
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  image: prismic.ImageField<never>;
}

/**
 * Primary content in *BaniereLogo → Default → Primary*
 */
export interface BaniereLogoSliceDefaultPrimary {
  /**
   * Titre field in *BaniereLogo → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: baniere_logo.default.primary.titre
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  titre: prismic.KeyTextField;

  /**
   * Images field in *BaniereLogo → Default → Primary*
   *
   * - **Field Type**: Group
   * - **Placeholder**: *None*
   * - **API ID Path**: baniere_logo.default.primary.images[]
   * - **Documentation**: https://prismic.io/docs/field#group
   */
  images: prismic.GroupField<
    Simplify<BaniereLogoSliceDefaultPrimaryImagesItem>
  >;

  /**
   * Label lien field in *BaniereLogo → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: baniere_logo.default.primary.label_lien
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  label_lien: prismic.KeyTextField;

  /**
   * Url lien field in *BaniereLogo → Default → Primary*
   *
   * - **Field Type**: Link
   * - **Placeholder**: *None*
   * - **API ID Path**: baniere_logo.default.primary.url_lien
   * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
   */
  url_lien: prismic.LinkField;
}

/**
 * Default variation for BaniereLogo Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type BaniereLogoSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<BaniereLogoSliceDefaultPrimary>,
  never
>;

/**
 * Slice variation for *BaniereLogo*
 */
type BaniereLogoSliceVariation = BaniereLogoSliceDefault;

/**
 * BaniereLogo Shared Slice
 *
 * - **API ID**: `baniere_logo`
 * - **Description**: BaniereLogo
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type BaniereLogoSlice = prismic.SharedSlice<
  "baniere_logo",
  BaniereLogoSliceVariation
>;

/**
 * Primary content in *Contact → Default → Primary*
 */
export interface ContactSliceDefaultPrimary {
  /**
   * Mail reception field in *Contact → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: contact.default.primary.mail_reception
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  mail_reception: prismic.KeyTextField;

  /**
   * Texte field in *Contact → Default → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: contact.default.primary.texte
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  texte: prismic.RichTextField;

  /**
   * Cle Google Map field in *Contact → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: contact.default.primary.cle_map
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  cle_map: prismic.KeyTextField;

  /**
   * Cle Google recaptcha v3 field in *Contact → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: contact.default.primary.cle_recaptcha
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  cle_recaptcha: prismic.KeyTextField;
}

/**
 * Default variation for Contact Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type ContactSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<ContactSliceDefaultPrimary>,
  never
>;

/**
 * Slice variation for *Contact*
 */
type ContactSliceVariation = ContactSliceDefault;

/**
 * Contact Shared Slice
 *
 * - **API ID**: `contact`
 * - **Description**: Contact
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type ContactSlice = prismic.SharedSlice<
  "contact",
  ContactSliceVariation
>;

/**
 * Primary content in *Format → Default → Primary*
 */
export interface FormatSliceDefaultPrimary {
  /**
   * Titre field in *Format → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: format.default.primary.titre
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  titre: prismic.KeyTextField;

  /**
   * Texte field in *Format → Default → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: format.default.primary.texte
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  texte: prismic.RichTextField;

  /**
   * Image 1 field in *Format → Default → Primary*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: format.default.primary.image_1
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  image_1: prismic.ImageField<never>;

  /**
   * Image 2 field in *Format → Default → Primary*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: format.default.primary.image_2
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  image_2: prismic.ImageField<never>;

  /**
   * Image 3 field in *Format → Default → Primary*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: format.default.primary.image_3
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  image_3: prismic.ImageField<never>;

  /**
   * Image 4 field in *Format → Default → Primary*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: format.default.primary.image_4
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  image_4: prismic.ImageField<never>;

  /**
   * Image 5 field in *Format → Default → Primary*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: format.default.primary.image_5
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  image_5: prismic.ImageField<never>;

  /**
   * Image 6 field in *Format → Default → Primary*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: format.default.primary.image_6
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  image_6: prismic.ImageField<never>;

  /**
   * Texte 1 ligne 1 field in *Format → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: format.default.primary.texte_1_ligne_1
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  texte_1_ligne_1: prismic.KeyTextField;

  /**
   * Texte 1 ligne 2 field in *Format → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: format.default.primary.texte_1_ligne_2
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  texte_1_ligne_2: prismic.KeyTextField;

  /**
   * Label 1 field in *Format → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: format.default.primary.label_1
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  label_1: prismic.KeyTextField;

  /**
   * URL 1 field in *Format → Default → Primary*
   *
   * - **Field Type**: Link
   * - **Placeholder**: *None*
   * - **API ID Path**: format.default.primary.url_1
   * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
   */
  url_1: prismic.LinkField;

  /**
   * Texte 2 ligne 1 field in *Format → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: format.default.primary.texte_2_ligne_1
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  texte_2_ligne_1: prismic.KeyTextField;

  /**
   * Texte 2 ligne 2 field in *Format → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: format.default.primary.texte_2_ligne_2
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  texte_2_ligne_2: prismic.KeyTextField;

  /**
   * Label 2 field in *Format → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: format.default.primary.label_2
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  label_2: prismic.KeyTextField;

  /**
   * URL 2 field in *Format → Default → Primary*
   *
   * - **Field Type**: Link
   * - **Placeholder**: *None*
   * - **API ID Path**: format.default.primary.url_2
   * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
   */
  url_2: prismic.LinkField;

  /**
   * Texte 3 ligne 1 field in *Format → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: format.default.primary.texte_3_ligne_1
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  texte_3_ligne_1: prismic.KeyTextField;

  /**
   * Texte 3 ligne 2 field in *Format → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: format.default.primary.texte_3_ligne_2
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  texte_3_ligne_2: prismic.KeyTextField;

  /**
   * Label 3 field in *Format → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: format.default.primary.label_3
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  label_3: prismic.KeyTextField;

  /**
   * URL 3 field in *Format → Default → Primary*
   *
   * - **Field Type**: Link
   * - **Placeholder**: *None*
   * - **API ID Path**: format.default.primary.url_3
   * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
   */
  url_3: prismic.LinkField;

  /**
   * Texte 4 ligne 1 field in *Format → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: format.default.primary.texte_4_ligne_1
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  texte_4_ligne_1: prismic.KeyTextField;

  /**
   * Texte 4 ligne 2 field in *Format → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: format.default.primary.texte_4_ligne_2
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  texte_4_ligne_2: prismic.KeyTextField;

  /**
   * Label 4 field in *Format → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: format.default.primary.label_4
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  label_4: prismic.KeyTextField;

  /**
   * URL 4 field in *Format → Default → Primary*
   *
   * - **Field Type**: Link
   * - **Placeholder**: *None*
   * - **API ID Path**: format.default.primary.url_4
   * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
   */
  url_4: prismic.LinkField;
}

/**
 * Default variation for Format Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type FormatSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<FormatSliceDefaultPrimary>,
  never
>;

/**
 * Slice variation for *Format*
 */
type FormatSliceVariation = FormatSliceDefault;

/**
 * Format Shared Slice
 *
 * - **API ID**: `format`
 * - **Description**: Format
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type FormatSlice = prismic.SharedSlice<"format", FormatSliceVariation>;

/**
 * Item in *Lieux → Default → Primary → Localisation*
 */
export interface LieuxSliceDefaultPrimaryLocalisationItem {
  /**
   * Background field in *Lieux → Default → Primary → Localisation*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: lieux.default.primary.localisation[].background
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  background: prismic.ImageField<never>;

  /**
   * Titre field in *Lieux → Default → Primary → Localisation*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: lieux.default.primary.localisation[].titre
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  titre: prismic.KeyTextField;
}

/**
 * Primary content in *Lieux → Default → Primary*
 */
export interface LieuxSliceDefaultPrimary {
  /**
   * Localisation field in *Lieux → Default → Primary*
   *
   * - **Field Type**: Group
   * - **Placeholder**: *None*
   * - **API ID Path**: lieux.default.primary.localisation[]
   * - **Documentation**: https://prismic.io/docs/field#group
   */
  localisation: prismic.GroupField<
    Simplify<LieuxSliceDefaultPrimaryLocalisationItem>
  >;
}

/**
 * Default variation for Lieux Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type LieuxSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<LieuxSliceDefaultPrimary>,
  never
>;

/**
 * Slice variation for *Lieux*
 */
type LieuxSliceVariation = LieuxSliceDefault;

/**
 * Lieux Shared Slice
 *
 * - **API ID**: `lieux`
 * - **Description**: Lieux
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type LieuxSlice = prismic.SharedSlice<"lieux", LieuxSliceVariation>;

/**
 * Primary content in *Media → Image → Primary*
 */
export interface MediaSliceDefaultPrimary {
  /**
   * Image field in *Media → Image → Primary*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: media.default.primary.image
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  image: prismic.ImageField<never>;
}

/**
 * Image variation for Media Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type MediaSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<MediaSliceDefaultPrimary>,
  never
>;

/**
 * Primary content in *Media → Video → Primary*
 */
export interface MediaSliceVideoPrimary {
  /**
   * Miniature field in *Media → Video → Primary*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: media.video.primary.miniature
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  miniature: prismic.ImageField<never>;

  /**
   * Video field in *Media → Video → Primary*
   *
   * - **Field Type**: Link to Media
   * - **Placeholder**: *None*
   * - **API ID Path**: media.video.primary.video
   * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
   */
  video: prismic.LinkToMediaField;
}

/**
 * Video variation for Media Slice
 *
 * - **API ID**: `video`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type MediaSliceVideo = prismic.SharedSliceVariation<
  "video",
  Simplify<MediaSliceVideoPrimary>,
  never
>;

/**
 * Slice variation for *Media*
 */
type MediaSliceVariation = MediaSliceDefault | MediaSliceVideo;

/**
 * Media Shared Slice
 *
 * - **API ID**: `media`
 * - **Description**: Media
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type MediaSlice = prismic.SharedSlice<"media", MediaSliceVariation>;

/**
 * Primary content in *Presentation → Default → Primary*
 */
export interface PresentationSliceDefaultPrimary {
  /**
   * Label lien top field in *Presentation → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: presentation.default.primary.label_lien_top
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  label_lien_top: prismic.KeyTextField;

  /**
   * Url lien top field in *Presentation → Default → Primary*
   *
   * - **Field Type**: Link
   * - **Placeholder**: *None*
   * - **API ID Path**: presentation.default.primary.url_lien_top
   * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
   */
  url_lien_top: prismic.LinkField;

  /**
   * Background field in *Presentation → Default → Primary*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: presentation.default.primary.background
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  background: prismic.ImageField<never>;

  /**
   * Titre field in *Presentation → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: presentation.default.primary.titre
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  titre: prismic.KeyTextField;

  /**
   * Contenu field in *Presentation → Default → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: presentation.default.primary.contenu
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  contenu: prismic.RichTextField;

  /**
   * Label lien field in *Presentation → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: presentation.default.primary.label_lien
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  label_lien: prismic.KeyTextField;

  /**
   * Url lien field in *Presentation → Default → Primary*
   *
   * - **Field Type**: Link
   * - **Placeholder**: *None*
   * - **API ID Path**: presentation.default.primary.url_lien
   * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
   */
  url_lien: prismic.LinkField;

  /**
   * Image field in *Presentation → Default → Primary*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: presentation.default.primary.image
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  image: prismic.ImageField<never>;
}

/**
 * Default variation for Presentation Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type PresentationSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<PresentationSliceDefaultPrimary>,
  never
>;

/**
 * Slice variation for *Presentation*
 */
type PresentationSliceVariation = PresentationSliceDefault;

/**
 * Presentation Shared Slice
 *
 * - **API ID**: `presentation`
 * - **Description**: Presentation
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type PresentationSlice = prismic.SharedSlice<
  "presentation",
  PresentationSliceVariation
>;

/**
 * Primary content in *Realisations → Default → Primary*
 */
export interface RealisationsSliceDefaultPrimary {
  /**
   * Titre field in *Realisations → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: realisations.default.primary.titre
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  titre: prismic.KeyTextField;

  /**
   * Image 1 field in *Realisations → Default → Primary*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: realisations.default.primary.image_1
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  image_1: prismic.ImageField<never>;

  /**
   * Titre 1 field in *Realisations → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: realisations.default.primary.titre_1
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  titre_1: prismic.KeyTextField;

  /**
   * texte 1 field in *Realisations → Default → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: realisations.default.primary.texte_1
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  texte_1: prismic.RichTextField;

  /**
   * Image 2 field in *Realisations → Default → Primary*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: realisations.default.primary.image_2
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  image_2: prismic.ImageField<never>;

  /**
   * Titre 2 field in *Realisations → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: realisations.default.primary.titre_2
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  titre_2: prismic.KeyTextField;

  /**
   * Texte 2 field in *Realisations → Default → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: realisations.default.primary.texte_2
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  texte_2: prismic.RichTextField;

  /**
   * Image 3 field in *Realisations → Default → Primary*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: realisations.default.primary.image_3
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  image_3: prismic.ImageField<never>;

  /**
   * Titre 3 field in *Realisations → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: realisations.default.primary.titre_3
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  titre_3: prismic.KeyTextField;

  /**
   * Texte 3 field in *Realisations → Default → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: realisations.default.primary.texte_3
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  texte_3: prismic.RichTextField;

  /**
   * label lien field in *Realisations → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: realisations.default.primary.label_lien
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  label_lien: prismic.KeyTextField;

  /**
   * Url lien field in *Realisations → Default → Primary*
   *
   * - **Field Type**: Link
   * - **Placeholder**: *None*
   * - **API ID Path**: realisations.default.primary.url_lien
   * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
   */
  url_lien: prismic.LinkField;
}

/**
 * Default variation for Realisations Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type RealisationsSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<RealisationsSliceDefaultPrimary>,
  never
>;

/**
 * Slice variation for *Realisations*
 */
type RealisationsSliceVariation = RealisationsSliceDefault;

/**
 * Realisations Shared Slice
 *
 * - **API ID**: `realisations`
 * - **Description**: Realisations
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type RealisationsSlice = prismic.SharedSlice<
  "realisations",
  RealisationsSliceVariation
>;

/**
 * Item in *Slider → Default → Primary → Slides*
 */
export interface SliderSliceDefaultPrimarySlidesItem {
  /**
   * Titre field in *Slider → Default → Primary → Slides*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: slider.default.primary.slides[].titre
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  titre: prismic.KeyTextField;

  /**
   * Texte field in *Slider → Default → Primary → Slides*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: slider.default.primary.slides[].texte
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  texte: prismic.RichTextField;

  /**
   * Image field in *Slider → Default → Primary → Slides*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: slider.default.primary.slides[].image
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  image: prismic.ImageField<never>;

  /**
   * Label lien field in *Slider → Default → Primary → Slides*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: slider.default.primary.slides[].label_lien
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  label_lien: prismic.KeyTextField;

  /**
   * Url lien field in *Slider → Default → Primary → Slides*
   *
   * - **Field Type**: Link
   * - **Placeholder**: *None*
   * - **API ID Path**: slider.default.primary.slides[].url_lien
   * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
   */
  url_lien: prismic.LinkField;
}

/**
 * Primary content in *Slider → Default → Primary*
 */
export interface SliderSliceDefaultPrimary {
  /**
   * Slides field in *Slider → Default → Primary*
   *
   * - **Field Type**: Group
   * - **Placeholder**: *None*
   * - **API ID Path**: slider.default.primary.slides[]
   * - **Documentation**: https://prismic.io/docs/field#group
   */
  slides: prismic.GroupField<Simplify<SliderSliceDefaultPrimarySlidesItem>>;
}

/**
 * Default variation for Slider Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type SliderSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<SliderSliceDefaultPrimary>,
  never
>;

/**
 * Slice variation for *Slider*
 */
type SliderSliceVariation = SliderSliceDefault;

/**
 * Slider Shared Slice
 *
 * - **API ID**: `slider`
 * - **Description**: Slider
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type SliderSlice = prismic.SharedSlice<"slider", SliderSliceVariation>;

/**
 * Primary content in *ImageTexte → Texte Image → Primary*
 */
export interface TestSliceDefaultPrimary {
  /**
   * Background field in *ImageTexte → Texte Image → Primary*
   *
   * - **Field Type**: Boolean
   * - **Placeholder**: *None*
   * - **Default Value**: false
   * - **API ID Path**: test.default.primary.background
   * - **Documentation**: https://prismic.io/docs/field#boolean
   */
  background: prismic.BooleanField;

  /**
   * Taille image field in *ImageTexte → Texte Image → Primary*
   *
   * - **Field Type**: Boolean
   * - **Placeholder**: *None*
   * - **Default Value**: false
   * - **API ID Path**: test.default.primary.taille_image
   * - **Documentation**: https://prismic.io/docs/field#boolean
   */
  taille_image: prismic.BooleanField;

  /**
   * Titre field in *ImageTexte → Texte Image → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: test.default.primary.titre
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  titre: prismic.KeyTextField;

  /**
   * Texte field in *ImageTexte → Texte Image → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: test.default.primary.texte
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  texte: prismic.RichTextField;

  /**
   * Label field in *ImageTexte → Texte Image → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: test.default.primary.label
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  label: prismic.KeyTextField;

  /**
   * Url field in *ImageTexte → Texte Image → Primary*
   *
   * - **Field Type**: Link
   * - **Placeholder**: *None*
   * - **API ID Path**: test.default.primary.url
   * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
   */
  url: prismic.LinkField;

  /**
   * Image field in *ImageTexte → Texte Image → Primary*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: test.default.primary.image
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  image: prismic.ImageField<never>;
}

/**
 * Texte Image variation for ImageTexte Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type TestSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<TestSliceDefaultPrimary>,
  never
>;

/**
 * Primary content in *ImageTexte → Image Texte → Primary*
 */
export interface TestSliceImageTextePrimary {
  /**
   * Background field in *ImageTexte → Image Texte → Primary*
   *
   * - **Field Type**: Boolean
   * - **Placeholder**: *None*
   * - **Default Value**: false
   * - **API ID Path**: test.imageTexte.primary.background
   * - **Documentation**: https://prismic.io/docs/field#boolean
   */
  background: prismic.BooleanField;

  /**
   * Taille image field in *ImageTexte → Image Texte → Primary*
   *
   * - **Field Type**: Boolean
   * - **Placeholder**: *None*
   * - **Default Value**: false
   * - **API ID Path**: test.imageTexte.primary.taille_image
   * - **Documentation**: https://prismic.io/docs/field#boolean
   */
  taille_image: prismic.BooleanField;

  /**
   * Titre field in *ImageTexte → Image Texte → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: test.imageTexte.primary.titre
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  titre: prismic.KeyTextField;

  /**
   * Texte field in *ImageTexte → Image Texte → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: test.imageTexte.primary.texte
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  texte: prismic.RichTextField;

  /**
   * Label field in *ImageTexte → Image Texte → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: test.imageTexte.primary.label
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  label: prismic.KeyTextField;

  /**
   * Url field in *ImageTexte → Image Texte → Primary*
   *
   * - **Field Type**: Link
   * - **Placeholder**: *None*
   * - **API ID Path**: test.imageTexte.primary.url
   * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
   */
  url: prismic.LinkField;

  /**
   * Image field in *ImageTexte → Image Texte → Primary*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: test.imageTexte.primary.image
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  image: prismic.ImageField<never>;
}

/**
 * Image Texte variation for ImageTexte Slice
 *
 * - **API ID**: `imageTexte`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type TestSliceImageTexte = prismic.SharedSliceVariation<
  "imageTexte",
  Simplify<TestSliceImageTextePrimary>,
  never
>;

/**
 * Slice variation for *ImageTexte*
 */
type TestSliceVariation = TestSliceDefault | TestSliceImageTexte;

/**
 * ImageTexte Shared Slice
 *
 * - **API ID**: `test`
 * - **Description**: Test
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type TestSlice = prismic.SharedSlice<"test", TestSliceVariation>;

/**
 * Primary content in *Titre → Light → Primary*
 */
export interface TitreSliceDefaultPrimary {
  /**
   * Titre field in *Titre → Light → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: titre.default.primary.titre
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  titre: prismic.KeyTextField;

  /**
   * Texte field in *Titre → Light → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: titre.default.primary.texte
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  texte: prismic.RichTextField;
}

/**
 * Light variation for Titre Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type TitreSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<TitreSliceDefaultPrimary>,
  never
>;

/**
 * Primary content in *Titre → Dark → Primary*
 */
export interface TitreSliceDarkPrimary {
  /**
   * Titre field in *Titre → Dark → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: titre.dark.primary.titre
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  titre: prismic.KeyTextField;

  /**
   * Texte field in *Titre → Dark → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: titre.dark.primary.texte
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  texte: prismic.RichTextField;
}

/**
 * Dark variation for Titre Slice
 *
 * - **API ID**: `dark`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type TitreSliceDark = prismic.SharedSliceVariation<
  "dark",
  Simplify<TitreSliceDarkPrimary>,
  never
>;

/**
 * Slice variation for *Titre*
 */
type TitreSliceVariation = TitreSliceDefault | TitreSliceDark;

/**
 * Titre Shared Slice
 *
 * - **API ID**: `titre`
 * - **Description**: Titre
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type TitreSlice = prismic.SharedSlice<"titre", TitreSliceVariation>;

declare module "@prismicio/client" {
  interface CreateClient {
    (
      repositoryNameOrEndpoint: string,
      options?: prismic.ClientConfig,
    ): prismic.Client<AllDocumentTypes>;
  }

  namespace Content {
    export type {
      FooterDocument,
      FooterDocumentData,
      FooterDocumentDataColonne1Item,
      FooterDocumentDataColonne2Item,
      FooterDocumentDataColonne3Item,
      FooterDocumentDataBottomItem,
      HeaderDocument,
      HeaderDocumentData,
      HeaderDocumentDataNavigationItem,
      HomepageDocument,
      HomepageDocumentData,
      HomepageDocumentDataSlicesSlice,
      PageDocument,
      PageDocumentData,
      PageDocumentDataSlicesSlice,
      SettingsDocument,
      SettingsDocumentData,
      AllDocumentTypes,
      BaniereLogoSlice,
      BaniereLogoSliceDefaultPrimaryImagesItem,
      BaniereLogoSliceDefaultPrimary,
      BaniereLogoSliceVariation,
      BaniereLogoSliceDefault,
      ContactSlice,
      ContactSliceDefaultPrimary,
      ContactSliceVariation,
      ContactSliceDefault,
      FormatSlice,
      FormatSliceDefaultPrimary,
      FormatSliceVariation,
      FormatSliceDefault,
      LieuxSlice,
      LieuxSliceDefaultPrimaryLocalisationItem,
      LieuxSliceDefaultPrimary,
      LieuxSliceVariation,
      LieuxSliceDefault,
      MediaSlice,
      MediaSliceDefaultPrimary,
      MediaSliceVideoPrimary,
      MediaSliceVariation,
      MediaSliceDefault,
      MediaSliceVideo,
      PresentationSlice,
      PresentationSliceDefaultPrimary,
      PresentationSliceVariation,
      PresentationSliceDefault,
      RealisationsSlice,
      RealisationsSliceDefaultPrimary,
      RealisationsSliceVariation,
      RealisationsSliceDefault,
      SliderSlice,
      SliderSliceDefaultPrimarySlidesItem,
      SliderSliceDefaultPrimary,
      SliderSliceVariation,
      SliderSliceDefault,
      TestSlice,
      TestSliceDefaultPrimary,
      TestSliceImageTextePrimary,
      TestSliceVariation,
      TestSliceDefault,
      TestSliceImageTexte,
      TitreSlice,
      TitreSliceDefaultPrimary,
      TitreSliceDarkPrimary,
      TitreSliceVariation,
      TitreSliceDefault,
      TitreSliceDark,
    };
  }
}
