// Code generated by Slice Machine. DO NOT EDIT.

import dynamic from "next/dynamic";

export const components = {
  baniere_logo: dynamic(() => import("./BaniereLogo")),
  contact: dynamic(() => import("./Contact")),
  format: dynamic(() => import("./Format")),
  lieux: dynamic(() => import("./Lieux")),
  media: dynamic(() => import("./Media")),
  presentation: dynamic(() => import("./Presentation")),
  realisations: dynamic(() => import("./Realisations")),
  slider: dynamic(() => import("./Slider")),
  test: dynamic(() => import("./ImageTexte")),
  titre: dynamic(() => import("./Titre")),
};
